### ISSUE TITLE
Need custom home label

### ISSUE THREAD

**Issue by rustedwolf** [jackton1/django-view-breadcrumbs#35]
Currently home label is static, but it's no good for projects that have locales other than just English. Needs to be configurable as well.

**Comment by jackton1** [comment]
It's currently supported to have a view specific home label using

```python

class TestDetailView(DetailBreadcrumbMixin, DetailView):
     model = TestModel
     home_label = _('My custom home')
     template_name = 'demo/test-detail.html'
```

**Comment by rustedwolf** [comment]
Yeah, I noticed, that I can do it that way and if I want to make it site-wise I might just create new classes out of mixins with that change.
Perhaps it's not big of a deal. Just had to go through all the code to figure it out. Maybe a little hint in the readme file would make it easier?

**Comment by jackton1** [comment]
Sure would update the readme also included support for a custom Home label site wide #37 .
