### ISSUE TITLE
Example for index page

### ISSUE THREAD

**Issue by saileshkush95** [jackton1/django-view-breadcrumbs#42]
Thanks for your works. But I'm facing problem when I'm trying to implement in index page please help me. I also want to pass custom httml class in template But i can't

**Comment by jackton1** [comment]
Sure, have you taken a look at the demo app https://github.com/jackton1/django-view-breadcrumbs/tree/master/demo or you could add some code snippets on where you're stuck.

**Comment by saileshkush95** [comment]
I mean,  that how can I use  BaseBreadcrumbMixin. In index page or home page
CreateBreadcrumbMixin works perfectly for model create view but when ever I replace model with form_class I'm getting error called attribute error for same view.
Any thanks for quick response.

**Comment by jackton1** [comment]
Oh okay you could simply add a crumbs property to the view.

```python

class RootView(BaseBreadcrumbMixin, ...):
    crumbs = [('Home', '')]

```

**Comment by saileshkush95** [comment]
Once again Thanks , But its not working here is my screenshot.
![Screenshot_20190723_073214](https://user-images.githubusercontent.com/28560875/61676572-3f0cbe00-ad1c-11e9-8887-0baf385ac286.png)
It doesn't display any things on index page. But in case of other views it works perfectly

**Comment by jackton1** [comment]
Here's a sample 

views.py
```python
class TestHomeView(BaseBreadcrumbMixin, TemplateView):
    template_name = 'demo/index.html'
    crumbs = []
```
urls.py
```python
# Home view
path('', views.TestHomeView.as_view(), name='test_root'),
```

index.html
```html
{% load django_bootstrap_breadcrumbs %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Test app</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    {% block breadcrumbs %}
    <main>
        {% render_breadcrumbs 'django_bootstrap_breadcrumbs/bootstrap4.html' %}
    </main>
    {% endblock %}
</body>
```

Which renders

<img width="1029" alt="Screen Shot 2019-07-23 at 1 11 35 AM" src="https://user-images.githubusercontent.com/17484350/61684288-eff86600-ace6-11e9-82b1-f704a84ec6ab.png">

**Comment by saileshkush95** [comment]
Thanks Dude
