### ISSUE TITLE
Not working properly for createview

### ISSUE THREAD

**Issue by saileshkush95** [jackton1/django-view-breadcrumbs#43]
Sorry for opening another issue. Its working fine if I use model for CreateView just like in below screenshot.
![Screenshot_20190723_072222](https://user-images.githubusercontent.com/28560875/61676711-b2163480-ad1c-11e9-86d8-0dbf96cb99fb.png)
But if use forms,  I'm getting errors like below.
![Screenshot_20190723_072125](https://user-images.githubusercontent.com/28560875/61676798-f86b9380-ad1c-11e9-860f-94413b9404c3.png)

![Screenshot_20190723_072329](https://user-images.githubusercontent.com/28560875/61676712-b2163480-ad1c-11e9-880b-756621767599.png)

Here is my Form
![Screenshot_20190723_074158](https://user-images.githubusercontent.com/28560875/61676942-72038180-ad1d-11e9-97ea-b5c72a12c976.png)

Here is my model
![Screenshot_20190723_075337](https://user-images.githubusercontent.com/28560875/61677371-1b974280-ad1f-11e9-9a8a-b223cbc96c1f.png)

**Comment by saileshkush95** [comment]
Issue solved

**Comment by jackton1** [comment]
This was because your view needs to specify a model for both cases.

```python
class UserCreateView(CreateBreadcrumbMixin, LoginRequiredMixin, CreateView):
    model = get_user_model()
```
